apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: ahujachirag/job-wq-2
        env:
        - name: REDIS_SERVICE_HOST
          value: localhost
      restartPolicy: OnFailure
